
from __future__ import annotations

from models.plan import FileEdit, ImplementationPlan
from prompts import SUMMARY_HEADER


class Summarizer:
    """Builds a markdown summary from a plan and the resulting file edits."""

    def summarize(self, plan: ImplementationPlan, edits: list[FileEdit]) -> str:
        lines = [SUMMARY_HEADER, ""]
        lines.append("## Modified Files")
        changed_edits = [edit for edit in edits if edit.changed]
        if changed_edits:
            lines.extend(f"- `{edit.path}`" for edit in changed_edits)
        else:
            lines.append("- No files were changed.")

        lines.append("")
        lines.append("## Features Added")
        lines.extend(f"- {feature}" for feature in plan.features)

        lines.append("")
        lines.append("## Reasoning")
        lines.append(plan.reasoning)

        lines.append("")
        lines.append("## Potential Risks")
        lines.extend(self._build_risks(plan, changed_edits))

        return "\n".join(lines)

    @staticmethod
    def _build_risks(plan: ImplementationPlan, changed_edits: list[FileEdit]) -> list[str]:
        risks = [
            "Changes were generated by an LLM and should be reviewed before merging.",
            "No automated tests were run against the modified files.",
        ]
        skipped = set(plan.files_to_modify) - {edit.path for edit in changed_edits}
        if skipped:
            skipped_list = ", ".join(f"`{path}`" for path in sorted(skipped))
            risks.append(f"These planned files were not updated: {skipped_list}.")
        return risks
